channels:
  - conda-forge
dependencies:
  - python=3.8.13
  - pip<=20.2.4
  - pip:
      - mlflow
      - cffi==1.15.1
      - dill==0.3.5.1
      - google-api-core==2.10.0
      - keras==2.7.0
      - pandas==1.3.5
      - pillow==9.2.0
      - scipy==1.7.3
      - tensorflow-gpu==2.7.4
      - tensorflow==2.7.4
      - azureml-inference-server-http
name: mlflow-env
